### ISSUE TITLE
About the Tweet Texts

### ISSUE THREAD

**Issue by zimuwangnlp** [jpmcair/tweetfinsent#1]
Dear Authors,

Thank you for your wonderful dataset for stock sentiment prediction, and I'm currently studying and researching your dataset. However, after downloading your dataset, I notice only the ids of the tweets are available, but not the tweet texts. Considering many of the tweets are unavailable after trying to fetch them using ids, is it possible for you to release the tweet texts in the dataset for reproduction and a fairer evaluation? Thank you.

Best Regards,
Zimu

**Comment by jpmcair** [comment]
Thank you for reaching out, Zimu. According to Twitter's API license, unfortunately, we cannot share the text. You have to use tweet ids in the dataset and then send them Twitter's API to collect text content.

- Shawn

**Comment by zimuwangnlp** [comment]
Dear Shawn,

Thanks for your response, and I understand Twitter's API license. However, I noticed some of the tweet texts are unaccessible; for instance, the users of the tweets may delete them after posting them on the platform, and they cannot be fetched by Twitter's API. Considering these tweets are annotated, is there a method for me to obtain these tweet texts? Thank you.

Best Regards,
Zimu
